### ISSUE TITLE
WebApiToSwaggerGenerator creates parameters with error "ONE_OF_MISSING"

### ISSUE THREAD

**Issue by jameschch** [NSwag/NSwag#477]
I've tried generating a swagger file for a webapi endpoint. When I take the json output to http://editor.swagger.io, I get the error ONE_OF_MISSING for several (all?) parameters.

Here's my generator code:

 ```
var swaggerSettings = new WebApiToSwaggerGeneratorSettings
            {
                DefaultPropertyNameHandling = NJsonSchema.PropertyNameHandling.CamelCase,
                DefaultUrlTemplate = "api/v0.1/{controller}/{id}",
                NullHandling = NJsonSchema.NullHandling.JsonSchema,
                GenerateKnownTypes = true,
                TypeNameGenerator = new DefaultTypeNameGenerator()
         
            };
            var swaggerGenerator = new WebApiToSwaggerGenerator(swaggerSettings);
            var document = swaggerGenerator.GenerateForController<CountriesController>();
            string json = document.ToJson();
```

and here's the resulting json:

```

{
  "swagger": "2.0",
  "info": {
    "title": "Web API Swagger specification",
    "version": "1.0.0"
  },
  "schemes": [],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/v0.1/Countries": {
      "get": {
        "tags": [
          "Countries"
        ],
        "operationId": "Countries_GetAll",
        "parameters": [
          {
            "type": "integer",
            "title": "GetAllCountriesModel_ZoneId",
            "name": "zoneId",
            "in": "query",
            "x-nullable": true
          },
          {
            "type": "string",
            "title": "String",
            "name": "search",
            "in": "query",
            "x-nullable": true
          },
          {
            "type": "integer",
            "name": "maximumPageSize",
            "in": "query",
            "x-nullable": false
          },
          {
            "type": "integer",
            "title": "PagingModel_Page",
            "name": "page",
            "in": "query",
            "x-nullable": false
          },
          {
            "type": "integer",
            "title": "PagingModel_PageSize",
            "name": "pageSize",
            "in": "query",
            "x-nullable": false
          },
          {
            "type": "boolean",
            "title": "PagingModel_Descending",
            "name": "descending",
            "in": "query",
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": [
                "array",
                "null"
              ],
              "items": {
                "$ref": "#/definitions/CountryModel"
              }
            },
            "x-nullable": true
          }
        }
      }
    },
    "/api/v0.1/Countries/{id}": {
      "get": {
        "tags": [
          "Countries"
        ],
        "operationId": "Countries_Get",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true,
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "file"
            },
            "x-nullable": true
          }
        }
      }
    }
  },
  "definitions": {
    "CountryModel": {
      "type": "object",
      "title": "CountryModel",
      "additionalProperties": false,
      "properties": {
        "countryCode": {
          "type": [
            "null",
            "string"
          ]
        },
        "countryName": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  },
  "responses": {},
  "securityDefinitions": {}
}
```

**Comment by rsuter** [comment]
NullHandling = NJsonSchema.NullHandling.JsonSchema,

Is not allowed for a Swagger specification.

**Comment by rsuter** [comment]
The spec has "title" properties in the parameters: 

    "title": "GetAllCountriesModel_ZoneId",

Where is this coming from? 

If you remove them and use NullHandling.Swagger then it should work...

**Comment by rsuter** [comment]
Sorry, the title is set by NSwag, I'll fix that...

**Comment by rsuter** [comment]
Strange, I cannot reproduce this, are you using NSwag v8.0?

**Comment by jameschch** [comment]
I am referencing nswag 8 (current latest on nuget). I have removed the line 

`
NullHandling = NJsonSchema.NullHandling.JsonSchema,`

...but still get the same error. It's great to know you're actively supporting this project.

One thing about the controller is it uses the [FromUri] attribute to bind parameter objects from the query string.

**Comment by rsuter** [comment]
NullHandling fixed some of the validation errors. 
This commit should fix the "title" validation errors: https://github.com/NJsonSchema/NJsonSchema/commit/09c795a624fddd3ecad6e72bf58ce41142dab04a

**Comment by rsuter** [comment]
I think this fixes the "title" problem: https://github.com/NJsonSchema/NJsonSchema/commit/5fdbe73fe92178d9b487137c4356bc1e7596f1bd

**Comment by rsuter** [comment]
Can you try with this NSwagStudio version? (I cannot reproduce this)

[NSwagStudio.zip](https://github.com/NSwag/NSwag/files/650471/NSwagStudio.zip)

**Comment by rsuter** [comment]
Please try again with v8.1

**Comment by jameschch** [comment]
Still getting the same validation error with 8.1. I will supply the json and then the swagger editor validation.
```

swagger: '2.0'
info:
  title: Web API Swagger specification
  version: 1.0.0
schemes: []
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v0.1/Countries:
    get:
      tags:
        - Countries
      operationId: Countries_GetAll
      parameters:
        - type: integer
          title: GetAllCountriesModel_ZoneId
          name: zoneId
          in: query
          x-nullable: true
        - type: string
          name: search
          in: query
          x-nullable: true
        - type: integer
          name: maximumPageSize
          in: query
          x-nullable: false
        - type: integer
          title: PagingModel_Page
          name: page
          in: query
          x-nullable: false
        - type: integer
          title: PagingModel_PageSize
          name: pageSize
          in: query
          x-nullable: false
        - type: boolean
          title: PagingModel_Descending
          name: descending
          in: query
          x-nullable: false
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CountryModel'
          x-nullable: true
  '/api/v0.1/Countries/{id}':
    get:
      tags:
        - Countries
      operationId: Countries_Get
      parameters:
        - type: string
          name: id
          in: path
          required: true
          x-nullable: false
      responses:
        '200':
          description: ''
          schema:
            type: file
          x-nullable: true
definitions:
  CountryModel:
    type: object
    additionalProperties: false
    properties:
      countryCode:
        type: string
      countryName:
        type: string
responses: {}
securityDefinitions: {}

```
```

Swagger Error

Not a valid parameter definition
Jump to line 39
Details
Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Not a valid parameter definition"
path: Array [5]
0: "paths"
1: "/api/v0.1/Countries"
2: "get"
3: "parameters"
4: "5"
schemaId: "http://swagger.io/v2/schema.json#"
inner: Array [2]
0: Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Data does not match any schemas from 'oneOf'"
path: Array [5]
0: "paths"
1: "/api/v0.1/Countries"
2: "get"
3: "parameters"
4: "5"
inner: Array [2]
0: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
params: Array [1]
0: "schema"
message: "Missing required property: schema"
path: Array [0]
1: Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Data does not match any schemas from 'oneOf'"
path: Array [0]
inner: Array [4]
0: Object
code: "OBJECT_ADDITIONAL_PROPERTIES"
params: Array [1]
0: Array [1]
0: "title"
message: "Additional properties not allowed: title"
path: Array [0]
1: Object
code: "OBJECT_ADDITIONAL_PROPERTIES"
params: Array [1]
0: Array [1]
0: "title"
message: "Additional properties not allowed: title"
path: Array [0]
2: Object
code: "OBJECT_ADDITIONAL_PROPERTIES"
params: Array [1]
0: Array [1]
0: "title"
message: "Additional properties not allowed: title"
path: Array [0]
3: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
params: Array [1]
0: "required"
message: "Missing required property: required"
path: Array [0]
1: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
params: Array [1]
0: "$ref"
message: "Missing required property: $ref"
path: Array [5]
0: "paths"
1: "/api/v0.1/Countries"
2: "get"
3: "parameters"
4: "5"
level: 900
type: "Swagger Error"
description: "Not a valid parameter definition"
lineNumber: 39

```

**Comment by rsuter** [comment]
Sorry, I cannot reproduce the problem.. Can you provide a sample project or at least the Web API controller code?

**Comment by jameschch** [comment]
I have added a project to recreate:

https://github.com/jameschch/webapisample

**Comment by rsuter** [comment]
You are using FromUri with a complex object... This should be easily fixed...

**Comment by jameschch** [comment]
Great I guessed it might be connected to fromui

**Comment by jameschch** [comment]
Will the fix for this issue be posted to nuget? I can still recreate with 8.1.6192

**Comment by rsuter** [comment]
The fix is not released yet, use the CI build artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts
